server:
  port: 8002
spring:
  application:
    name: consumer-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 1 #向eureka服务端发送心跳包间隔时间(默认：30s)
    lease-expiration-duration-in-seconds: 2  #自eureka服务器接收到上一次心跳以来可以等待的时间（以秒为单位），之后它才能从其视图中删除该实例，并通过禁止向该实例的流量进行操作(默认：90s)
###设置feign客户端超时时间
###SpringCloud feign 默认开启支持ribbon
ribbon:
  ReadTimeout: 5000 #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ConnectTimeout: 5000  #指的是建立连接后从服务器读取到可用资源所用的时间。
feign:
  hystrix:
    enabled: true #开启hystix断路器
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #设置超时时间